language: node_js
node_js:
  - 12.6
cache:
  directories:
    - node_modules
before_script:
  - npm install
notifications:
  email:
    - hiteshnagda@adit.com

script: 
  - npm run tslint
  
branches: 
  only:
    - master