language: node_js

node_js:
  - 12.6

services: mongodb

cache:
  directories:
    - node_modules

before_script:
  - npm install

script: 
  - npm run start
  - npm run tslint

branches: 
  only:
    - master