language: node_js

node_js:
  - 12.6

services: mongodb

cache:
  directories:
    - node_modules

before_script:
  - npm install

jobs:
  include:
    - stage: lint
      name: "Linting Test"
      script: npm run tslint 

branches: 
  only:
    - master