language: node_js

node_js:
  - 12.6
  - 10.16

cache:
  directories:
    - node_modules

before_script:
  - npm install

script: 
  - npm run tslint
  - npm run start
  
branches: 
  only:
    - master